### ISSUE TITLE
Page title

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/base_meta#1]
Vladimir, thank you very much for this module!
This is very valuable thing.
"Some people cannot adopt CMS without such (even very basic) functionality." - yes, it is about me.

Well, the only thing I think it would be good to change/improve - Page title field.
If we type our custom title in then we do not get fully customized title - we get:

    <title>our custom title | default website title</title>

I think best and right variant is fully custom title without adding the default one:

    <title>our custom title</title>

**Comment by findlabnet** [comment]
@bd0bd, thank you for your warm words. Good to know - when I wrote about "some people" - you personally was in my mind as first one of many others SEO-oriented users.

Second part of page title - "| default website title" was temporary hard coded for titles structure back compatibility, but you right - it should be only optionally.

**Comment by bd0bd** [comment]
> many others *SEO-oriented** users.

A **business oriented** might be more appropriate/correct wording :)

**Comment by bd0bd** [comment]
May be it is better to remove word **Base** from **Base meta tags, page title**.
May be this variant is better?: **Meta tags and page title** or **Page title and meta tags**.
In my mind **Page title and meta tags** is more correct.

![module](https://cloud.githubusercontent.com/assets/13515302/10714793/76366e14-7b0f-11e5-9638-b8a690a16ba2.gif)

**Comment by bd0bd** [comment]
**this(or default)** - gap.

"Use a relative URL without the initial slash for this(or default) domain or full URL in oter case. By             default (if no value) this will automatically use URL of this page."

**Comment by findlabnet** [comment]
Thank you very much @bd0bd for your QA work. You already prepare for me a set of changes for new release.

**Comment by bd0bd** [comment]
I think (from my many years experience with this issue) would be good not to have any required fields.
If I need to change title only why I am required to fill "Description" field if I do not need it? :)

Will you remove **"| default website title" ** in new release or I need to modify my templates?

**Comment by findlabnet** [comment]
OK, if you let me day or two :-)

**Comment by bd0bd** [comment]
Thank you! :-)

**Comment by findlabnet** [comment]
Released https://github.com/backdrop-contrib/base_meta/releases/tag/1.x-1.1.0
Please test.

**Comment by bd0bd** [comment]
Thank you very much!
I am very happy you have created this module!

I will test it later (will update my website pages) and will let you know if something is wrong etc.

Now I can tell this thing. Currently the HTML order is like this:

    <meta name="description" content="" />
    <meta name="Generator" content="Backdrop CMS 1 (http://backdropcms.org)" />
    <meta name="keywords" content="" />
    <title></title>

Would be good to reorder like this:

    <meta name="Generator" content="Backdrop CMS 1 (http://backdropcms.org)" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <title></title>

But even more right or beautiful way would be:

    <title></title>
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="Generator" content="Backdrop CMS 1 (http://backdropcms.org)" />
