### ISSUE TITLE
Could not delete temporary file "temporary://base_meta-1.x_1.zip" during garbage 

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/base_meta#11]
In **/admin/reports/dblog**

I see this report every day:

**Could not delete temporary file "temporary://base_meta-1.x_1.zip" during garbage collection**

**Comment by findlabnet** [comment]
This message going from system.module - for some reason your database still have record about non-existing temporary file (maybe deleted by hand or when filesystem was restored from backup/moved between servers), so any cron run - system try to remove expired file, but cannot find it.
To fix current state just find in table `file_managed` record where `uri` is "temporary://base_meta-1.x_1.zip" an remove this record.

**Comment by bd0bd** [comment]
Thank you! I do not have any problems with this issue. I only would like to inform you about this matter.

I do not have similar issues with other modules.

**Comment by findlabnet** [comment]
Thank you for cooperation, but this issue not related to module.
