### ISSUE TITLE
How far does this module take us for SEO support?

### ISSUE THREAD

**Issue by PaulHoza** [backdrop-contrib/base_meta#2]
I'm not sure where else to pose this question, but is this module, along with the other "Custom Meta" module (https://github.com/backdrop-contrib/custom_meta), getting us roughly to the same place as the D7 module "Metatag"? (https://www.drupal.org/project/metatag)

I've got a client who's freakishly-worried about SEO stuff and that's been one of the few things I may be stuck going with D7 for this build.  I'm concerned I can't get the SEO "stuff" up to a similar level as he's used to with his old WordPress site using a popular SEO plugin (the Yoast one, btw.)  I need to get pretty close to the core features of that plugin or I don't think he'll buy in, regardless of whether it's really necessary or not.

Another question to ask would be: what is the status of Backdrop's SEO feature set? Is this module roughly "good enough", or are there other features we need to get rolled in?  I need to refresh my memory on the Metatag module for D7, to make sure I remember all the stuff it can do.

Thanks for any feedback.

**Comment by findlabnet** [comment]
Hi Paul, thanks for your question. 
My motivation to work with this module - exactly this type of "client who's freakishly-worried about SEO stuff", so I'm not a right person who can tell you "if this module *roughly good enough*".
Right now core doesn't have even this minimal functionality. 
I did my little work in hope to help someone start using Backdrop CMS already today, before we can have very complex Drupal-like modules, because it can take some more time.
Maybe someone else can add something?

**Comment by bd0bd** [comment]
> I did my little work in hope to help someone start using Backdrop CMS already today

I am very much thankful to you for this module.
I was going to switch from Backdrop to Drupal because of this key business issue.

**Comment by LeeteqXV** [comment]
Ref. my question about 3 meta modules here:
"Why are there 3 meta tag modules?"
https://github.com/backdrop-contrib/seo_meta/issues/8

**Comment by findlabnet** [comment]
Hi @LeeteqXV, 
as you can see in corresponds README.md  files,  this module is discontinued in favor of [SEO Meta Tags](https://backdropcms.org/project/seo_meta).

**Comment by LeeteqXV** [comment]
Ok, I had a quick read up on what those modules did, but did not scroll down to read it all before I had looked briefly at the others, so I missed that part by just a few centimetres... And wasted both my own and your time as a result.

I suggest saving us from this type of unnecessary question in the future, as it is both in the Readme and on the module page, by placing such cancellation messages **on top** of those pages, not at the bottom...

**When a project is cancelled, maybe we should have a category for that which also automagically colored the background of the project page somewhat differently (light redish?) to notify any page visitor of that status.**

**Comment by findlabnet** [comment]
Not relevant anymore.
