### ISSUE TITLE
How to apply it to Views pages

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/base_meta#3]
I have 2 views pages - Articles and Books.
Do not understand how to apply it to these views.
No way? :)

**Comment by findlabnet** [comment]
Not yet. Planned add support for views pages.

**Comment by bd0bd** [comment]
Would be good.
Will be waiting :-)
Thank you!

**Comment by findlabnet** [comment]
Hi @bd0bd, see version 1.1.1, maybe this help.
