### ISSUE TITLE
Rename module name Base Meta Tags 

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/base_meta#4]
**Vladimir**, may be it would be better to rename the current name of your module https://backdropcms.org/project/base_meta

**Base Meta Tags**

to

**Page Title and Meta Tags**

Page title is very key element of this module. When I have searched modules on Drupal site I have firstly asked for "page title".

I think **Page Title and Meta Tags** - is more clear and appropriate name. I think this name will help the people to find this module when they search for it.

**Comment by findlabnet** [comment]
My initial idea was "Base (or basic) Set of Meta Tags".
From here this name, "...quest for simplicity", you remember? 
But, maybe even simple things should be more complex today. :-) 
I'll think about next step.

**Comment by bd0bd** [comment]
**base** and **set** are general (common) words - something like a garbage words here.
A simplicity you talk about, should be applied where it is appropriate.
All depends on the situations.
Situations can be different.
Sometimes we should forget this formula - **quest for simplicity** - and make it in the way other people would understand what is purpose of this module. The name **Page Title and Meta Tags** is expressing more clear what it is about/for than the name **Base Set of Meta Tags**.
I am sure 100% that **Page Title and Meta Tags** is better name for this module.

Well, if you need simple name then it could be **SEO Simple** or **Simple SEO**.
:-)

Thank you!

**Comment by findlabnet** [comment]
The development of this module is moved to a new one - [SEO Meta Tags](https://github.com/backdrop-contrib/seo_meta).
For bug reports, feature or support requests, please use the module issue queue at https://github.com/backdrop-contrib/seo_meta/issues.
