### ISSUE TITLE
Default title is added again

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/base_meta#5]
Hm, something like a mirical.
I have updated the module, renamed the title one or two days ago - everything was ok.
And now the titles are again the same they were before - with the default part of title.
I do not understand what has happened.

**Comment by bd0bd** [comment]
UPDATE
O, now I can see the option in the module settings:

**Append site name to page title**

But I do not understand why it was automatically appended.
It was not before.

**Comment by findlabnet** [comment]
This new option turned on by default for backward compatibility, but you can disable it.

**Comment by bd0bd** [comment]
Thank you!
