### ISSUE TITLE
Upgrade from other modules

### ISSUE THREAD

**Issue by sherifmayika** [backdrop-contrib/base_meta#6]
Hello,
I have a site running on D7 and and I using Metatag quick and Page title modules. I am just wondering can I use this module to upgrade my site to Backdrop? is such functionality available? Or else can you add that?

Thanks in advance
Aladin
[Party organizer in Cochin](http://www.sherifmayika.com)

**Comment by findlabnet** [comment]
Hello @sherifmayika, thank you for your interest to this module. Basic functionality available as described in the file "README.md ".
Please pay attention: this module is new and and have no way to upgrade from D7. 
Views and taxonomy pages at this time can use only default values (if set up in module) not unique for each one. 
In next relise I plan add support for such pages, but can not promise when that will happen - maybe two weeks or more.

**Comment by sherifmayika** [comment]
findlabnet ,
Thanks for the reply. 
I got stuck when I tried to port Page title and Metatag Quick. Meanwhile I noticed your module.
I will try porting both modules this week. If they work fine I will upload here. 

I have a feeling that new CMS should not have many modules with same functionality. Which make only confusion to the users. This is why I asked you if your module provide an upgrade from other seo modules

thanks 
Aladin
[Birthday Party organizer in Cochin](http://www.sherifmayika.com)

**Comment by findlabnet** [comment]
Aladin, thank you!

> ... should not have many modules with same functionality.

Why? One world, one ocean, one language, one windows 10, one ubuntu? But I use another Linux distro, so I wrong?
For me - anyone can have such wide choice from many things as possible - it is the spirit of OSS.
You free in your choice - so best regards!
Don't get words above so seriously, just for fun ;-)
Vladimir.

**Comment by findlabnet** [comment]
Not relevant anymore.
