### ISSUE TITLE
Undefined property Error --- Webform module

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/base_meta#7]
Hi!

It is not a problem for me, it is for your information:

![webform_meta](https://cloud.githubusercontent.com/assets/13515302/11448774/1370f6e2-9571-11e5-8ebe-756928f559ac.png)

This happens after editing and saving the Form settings of Webform module:

![save_webform](https://cloud.githubusercontent.com/assets/13515302/11448803/dededec0-9571-11e5-8940-834380ae944e.png)

Thank you!

**Comment by findlabnet** [comment]
I don't use "Webform" module - so not tested yet. When I have some spare time - I work for your previous requests ;-)

**Comment by bd0bd** [comment]
Probably you do mean the Views issue - it would be very good of cause :) Thank you!

**Comment by findlabnet** [comment]
Thanks @bd0bd, there was a bug. Fixed in version 1.1.1
