### ISSUE TITLE
Hide Meta robots and Canonical URL on node edit form

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/base_meta#8]
Hi!

I offer to hide a part of settings Meta robots and Canonical URL:

![aaa](https://cloud.githubusercontent.com/assets/13515302/14213076/b4f47040-f83e-11e5-8d7c-fd2a0bb0bd51.png)

**Comment by findlabnet** [comment]
You're right, so it looks better. Tomorrow (not at 1 April.)

**Comment by bd0bd** [comment]
I am not sure but from my point of view the overall look of editing page would be a little bit better, clean
But this issue is actual only if **Page title and meta tags** menu tab is on the top - it takes too much space right at the home of edit page:

![ttt](https://cloud.githubusercontent.com/assets/13515302/14218537/724665e0-f85d-11e5-9422-15dfefb808c4.png)

**Comment by findlabnet** [comment]
Released version 1.x-1.1.2 with this change only.

**Comment by bd0bd** [comment]
Thank you! Very nice.

But the version number - 1.1.1 - remains unchanged here - https://github.com/backdrop-contrib/base_meta
