### ISSUE TITLE
Want to add basic Open Graph tags?

### ISSUE THREAD

**Issue by chellman** [backdrop-contrib/base_meta#9]
I forked this module for a project and added basic open graph meta tags (og_title, og_description, og_image, og_url, og_type).  Is this something you'd like to have in the module?  If so, I'll backport and submit a PR.

**Comment by findlabnet** [comment]
Thanks @chellman, we can place this set of tags too. But FYI - I'm very busy some few days, so not sure when I can to do this.

**Comment by chellman** [comment]
No worries - thanks for writing back.  I've done enough to get nodes working (pull request is in), which is what I needed for now. If it looks good, and you don't have the time for it, I can look at views and taxonomy a little later.

**Comment by findlabnet** [comment]
@chellman, I really feel wrong myself when you waiting for my answer, so first of all: thank you for your impressive work. 
I just have a few minor comments below.
1) When I trying to update to version 1.1.3, I got 
`"PDOException: SQLSTATE[22004]: Null value not allowed: 1138 Invalid use of NULL value: ALTER TABLE {base_meta} CHANGE `meta_og_url` `meta_og_url` VARCHAR(255) NOT NULL COMMENT 'Meta open graph URL.'; Array ( ) in db_add_field() (line 2847 of /path_to/domain.tld/core/includes/database/database.inc)."`

To avoid this, we can try add to field definition one more parameter: `'default' => '',` both for schema and schema update.

2) When I trying to save node after edit, I got
`"Notice: Undefined index: meta_canonical in base_meta_record_update() (line 396 of /path_to/domain.tld/modules/contrib/base_meta/base_meta.module)."`
So, we can or simple fix 
`$meta_og_url = trim($node->base_meta['meta_canonical']);`
to 
`$meta_og_url = trim($node->base_meta['group']['meta_canonical']);`
or just say
`$meta_og_url = $meta_canonical;`
Or, if we dont need separate variable, we can just say on line 410:
`'meta_og_url' => $meta_canonical,` and remove line 396 at all.

3) If we do definition for meta canonical in node form - base part of URL lost for "og:url".

4) Line 207 in module:
`'#upload_location' => 'public://files/og_image',`
but we have defined such value in config, 
so if we get it from config, we can avoid this strange status which we have now:
- one picture placed to `files/og_image/aaa.png` (from module settings page)
- second picture placed to `files/files/og_image/bbb.png` (from node edit form)

5) How you plan to use default values, defined in module settings page? Not in use right now?

Thank you!

**Comment by chellman** [comment]
Thanks for the comments! I think all these issues are fixed now. Comments:

1) I think it makes sense to allow the og:url to be null since canonical can (and we have defaults for the tags), so I updated the schema.

2 and 3) I got rid of the separate variables for meta_og_url.  I think it makes sense to just use canonical if we have one set, and use the default otherwise.

4) Fixed - using the location from config now.

5) Same as what you're already doing with the other tags - using them if no other values are present.

**Comment by chellman** [comment]
Just added a commit that swaps [] for array() in the .install file - PHP 5.3 is supported by Backdrop, so that had to change.

**Comment by findlabnet** [comment]
Thanks @chellman, on weekend I'll be back :-)

**Comment by findlabnet** [comment]
I've merged your PR @chellman , thanks.  
Please note, fields for default values not in use for now, we can only change image directory location from this fieldset. In my opinion we cannot release module with such behavior.

**Comment by chellman** [comment]
Great about the merge.  About the default field use, I'm not sure what you mean, but I'll help fix it if I can.

Are you saying that having the image location controlled completely by the default setting is not a good thing?  Considering this module's modest set of tags, I assumed that keeping things as simple as possible was good.  But please do let me know what you're thinking about it.

**Comment by findlabnet** [comment]
I meant "default values" for OG tags not in use (not printed out even if defined) but "image directory location" is only one thing what works from this fieldset (and this is good thing).
Small clarification: English is only third language in my daily life, so if something not so clear for you as I expect - I'm sorry, just let me know about it.

**Comment by bd0bd** [comment]
Sorry, I do not understand how to activate OG meta :)
I do not have it added in webpages HTML.
Thank you!

**Comment by findlabnet** [comment]
@bd0bd,  this functionality not in latest release (1.x-1.1.2) yet - some more work is needed, but you can try current code from https://github.com/backdrop-contrib/base_meta.
Anyway, **I must remind again:** this module was released as temporary workaround only and not intended for "enterprise" level solution. Maybe next attempt will be better.

**Comment by bd0bd** [comment]
I see. Thank you!
I do not know what is 'enterprise'. OG meta would be enough without any enterprise:)
I would like to hope you will implement this function soon because your module is very valueable and it saves our life.

**Comment by bd0bd** [comment]
@findlabnet, thank you very much!
It is very cool now! :smile:

**Comment by bd0bd** [comment]
Is it possible to move down <meta name="viewport" content="width=device-width, initial-scale=1" />?

Right now the order is like this:

<meta name="og:url" content="http://domain.com" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="og:type" content="website" />
<meta name="og:title" content="Title" />

It should be:

<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="og:url" content="http://domain.com" />
<meta name="og:type" content="website" />
<meta name="og:title" content="Title" />

or

<meta name="og:url" content="http://domain.com" />
<meta name="og:type" content="website" />
<meta name="og:title" content="Title" />
<meta name="viewport" content="width=device-width, initial-scale=1" />

**Comment by findlabnet** [comment]
The development of this module is moved to a new one - [SEO Meta Tags](https://github.com/backdrop-contrib/seo_meta).
Current issue resolved in new module.
For bug reports, feature or support requests, please use the module issue queue at https://github.com/backdrop-contrib/seo_meta/issues.
